version: '3.6'
services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-api-server-container
    expose:
      - '8000'
    ports:
      - '8000:8000'
    restart: on-failure
    command: node server.js
    env_file: ./env/.env.prod
  task-queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-data-fetch-queue-container
    restart: on-failure
    command:  bash -c "node syncDatabase.js && node fetchApiQueue.js"
    env_file: ./env/.env.prod
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    expose:
      - '5432'
    ports:
      - "5432:5432"
  redis:
    image: 'bitnami/redis:latest'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    expose:
      - '6379'
    ports:
      - "6379:6379"
volumes:
  db_data:
